/** Cómo se lee cada acción del historial (docs/01-analisis.md §7). */
export const NOMBRES_DE_ACCIONES: Record<string, string> = {
  ORGANIZACION_REGISTRADA: 'Organización registrada',
  SESION_INICIADA: 'Inicio de sesión',
  SESION_FALLIDA: 'Inicio de sesión fallido',
  SESION_CERRADA: 'Cierre de sesión',
  CLAVE_CAMBIADA: 'Contraseña cambiada',
  USUARIO_CREADO: 'Usuario creado',
  USUARIO_EDITADO: 'Usuario editado',
  USUARIO_DESACTIVADO: 'Usuario desactivado',
  USUARIO_REACTIVADO: 'Usuario reactivado',
  CATEGORIA_CREADA: 'Categoría creada',
  CATEGORIA_EDITADA: 'Categoría editada',
  DOCUMENTO_SUBIDO: 'Documento subido',
  DOCUMENTO_EDITADO: 'Documento editado',
  DOCUMENTO_ELIMINADO: 'Documento eliminado',
  DOCUMENTO_VISUALIZADO: 'Documento visto',
  DOCUMENTO_DESCARGADO: 'Documento descargado',
  BUSQUEDA_REALIZADA: 'Búsqueda',
  SOLICITUD_CREADA: 'Aprobación solicitada',
  SOLICITUD_APROBADA: 'Solicitud aprobada',
  SOLICITUD_RECHAZADA: 'Solicitud rechazada',
  ACCESO_DENEGADO: 'Acceso denegado',
  HISTORIAL_EXPORTADO: 'Historial exportado',
};
